# Generated by Django 4.1.7 on 2023-11-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etrap', models.CharField(blank=True, max_length=32, null=True, verbose_name='Этрап')),
                ('account', models.CharField(blank=True, max_length=8, null=True, verbose_name='Счёт')),
                ('AccountName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя счет №')),
                ('AccountAdress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес счет №')),
            ],
            options={
                'verbose_name': 'БД для Счет №',
                'verbose_name_plural': 'БД для Счет №',
            },
        ),
    ]
