# Generated by Django 4.1.7 on 2023-11-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0002_accountname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountname',
            old_name='AccountAdress',
            new_name='accountAdress',
        ),
        migrations.RenameField(
            model_name='accountname',
            old_name='AccountName',
            new_name='accountName',
        ),
    ]
