# Generated by Django 4.1.7 on 2023-11-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0003_rename_accountadress_accountname_accountadress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='kassa',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Касса №'),
        ),
    ]
