# Generated by Django 4.1.7 on 2023-12-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0004_payhistory_kassa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='s_alem',
            field=models.FloatField(default=0, verbose_name=' Сальдо Alem TV'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='s_dop_uslugi',
            field=models.FloatField(default=0, verbose_name='Сальдо Доп. Услуги'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='s_internet',
            field=models.FloatField(default=0, verbose_name=' Сальдо Интернет'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='s_kabel',
            field=models.FloatField(default=0, verbose_name=' Сальдо Кабель'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='s_kod',
            field=models.FloatField(default=0, verbose_name='Сальдо Код'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='s_prochee',
            field=models.FloatField(default=0, verbose_name='Сальдо Прочее'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='s_slr',
            field=models.FloatField(default=0, verbose_name='Сальдо СЛР'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='s_telefon',
            field=models.FloatField(default=0, verbose_name='Сальдо Телефон'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='s_zakaz',
            field=models.FloatField(default=0, verbose_name='Сальдо Заказ'),
        ),
        migrations.AddField(
            model_name='usertablearhiw',
            name='s_alem',
            field=models.FloatField(default=0, verbose_name=' Сальдо Alem TV'),
        ),
        migrations.AddField(
            model_name='usertablearhiw',
            name='s_dop_uslugi',
            field=models.FloatField(default=0, verbose_name='Сальдо Доп. Услуги'),
        ),
        migrations.AddField(
            model_name='usertablearhiw',
            name='s_internet',
            field=models.FloatField(default=0, verbose_name=' Сальдо Интернет'),
        ),
        migrations.AddField(
            model_name='usertablearhiw',
            name='s_kabel',
            field=models.FloatField(default=0, verbose_name=' Сальдо Кабель'),
        ),
        migrations.AddField(
            model_name='usertablearhiw',
            name='s_kod',
            field=models.FloatField(default=0, verbose_name='Сальдо Код'),
        ),
        migrations.AddField(
            model_name='usertablearhiw',
            name='s_prochee',
            field=models.FloatField(default=0, verbose_name='Сальдо Прочее'),
        ),
        migrations.AddField(
            model_name='usertablearhiw',
            name='s_slr',
            field=models.FloatField(default=0, verbose_name='Сальдо СЛР'),
        ),
        migrations.AddField(
            model_name='usertablearhiw',
            name='s_telefon',
            field=models.FloatField(default=0, verbose_name='Сальдо Телефон'),
        ),
        migrations.AddField(
            model_name='usertablearhiw',
            name='s_zakaz',
            field=models.FloatField(default=0, verbose_name='Сальдо Заказ'),
        ),
    ]
