# Generated by Django 4.1.7 on 2023-12-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0005_usertable_s_alem_usertable_s_dop_uslugi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachisleniyaotchet',
            name='perek_edara_debit_minus',
            field=models.FloatField(default=0, verbose_name='Перекидка c edara Дебит (-)'),
        ),
        migrations.AddField(
            model_name='nachisleniyaotchet',
            name='perek_edara_debit_plus',
            field=models.FloatField(default=0, verbose_name='Перекидка на edara Дебит (-)'),
        ),
        migrations.AddField(
            model_name='nachisleniyaotchet',
            name='perek_edara_kredit_minus',
            field=models.FloatField(default=0, verbose_name='Перекидка c edara Кредит (+)'),
        ),
        migrations.AddField(
            model_name='nachisleniyaotchet',
            name='perek_edara_kredit_plus',
            field=models.FloatField(default=0, verbose_name='Перекидка на edara Кредит (+)'),
        ),
        migrations.AddField(
            model_name='nachisleniyaotchet',
            name='perek_nasel_debit_minus',
            field=models.FloatField(default=0, verbose_name='Перекидка c населения Дебит (-)'),
        ),
        migrations.AddField(
            model_name='nachisleniyaotchet',
            name='perek_nasel_debit_plus',
            field=models.FloatField(default=0, verbose_name='Перекидка на населения Дебит (-)'),
        ),
        migrations.AddField(
            model_name='nachisleniyaotchet',
            name='perek_nasel_kredit_minus',
            field=models.FloatField(default=0, verbose_name='Перекидка c населения Кредит (+)'),
        ),
        migrations.AddField(
            model_name='nachisleniyaotchet',
            name='perek_nasel_kredit_plus',
            field=models.FloatField(default=0, verbose_name='Перекидка на населения Кредит (+)'),
        ),
    ]
