# Generated by Django 4.1.7 on 2023-12-24 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telekom', '0006_nachisleniyaotchet_perek_edara_debit_minus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerekidkaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1Number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Перекинуто с абонента номер')),
                ('user1Etrap', models.CharField(blank=True, max_length=255, null=True, verbose_name='Перекинуто с абонента этрап')),
                ('user2Number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Перекинуто на абонента номер')),
                ('user2Etrap', models.CharField(blank=True, max_length=255, null=True, verbose_name='Перекинуто на абонента этрап')),
                ('user1_is_enterprises', models.BooleanField(default=False, verbose_name='Абонент 1 предпр')),
                ('user2_is_enterprises', models.BooleanField(default=False, verbose_name='Абонент 2 предпр')),
                ('internet1', models.FloatField(default=0, verbose_name='Перекинуто с Интернет')),
                ('kabel1', models.FloatField(default=0, verbose_name=' Перекинуто с Кабель')),
                ('alem1', models.FloatField(default=0, verbose_name=' Перекинуто с Alem TV')),
                ('telefon1', models.FloatField(default=0, verbose_name='Перекинуто с Телефон')),
                ('slr1', models.FloatField(default=0, verbose_name='Перекинуто с СЛР')),
                ('kod1', models.FloatField(default=0, verbose_name='Перекинуто с Код')),
                ('zakaz1', models.FloatField(default=0, verbose_name='Перекинуто с Заказ')),
                ('prochee1', models.FloatField(default=0, verbose_name='Перекинуто с Прочее')),
                ('dop_uslugi1', models.FloatField(default=0, verbose_name='Перекинуто с Доп. Услуги')),
                ('internet2', models.FloatField(default=0, verbose_name='Перекинуто на Интернет')),
                ('kabel2', models.FloatField(default=0, verbose_name=' Перекинуто на Кабель')),
                ('alem2', models.FloatField(default=0, verbose_name=' Перекинуто на Alem TV')),
                ('telefon2', models.FloatField(default=0, verbose_name='Перекинуто на Телефон')),
                ('slr2', models.FloatField(default=0, verbose_name='Перекинуто на СЛР')),
                ('kod2', models.FloatField(default=0, verbose_name='Перекинуто на Код')),
                ('zakaz2', models.FloatField(default=0, verbose_name='Перекинуто на Заказ')),
                ('prochee2', models.FloatField(default=0, verbose_name='Перекинуто на Прочее')),
                ('dop_uslugi2', models.FloatField(default=0, verbose_name='Перекинуто на Доп. Услуги')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('createDate', models.DateField(auto_now_add=True, verbose_name='Дата перекидки')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Информация о перекидках',
                'verbose_name_plural': 'Информация о перекидках',
            },
        ),
    ]
