# Generated by Django 4.1.7 on 2024-01-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0007_perekidkainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldLoginDogowor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер')),
                ('etrap', models.CharField(blank=True, max_length=64, null=True, verbose_name='Этрап')),
                ('login', models.CharField(blank=True, max_length=32, verbose_name='Логин')),
                ('dogowor', models.CharField(blank=True, max_length=32, verbose_name='Договор')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name': 'Старые договоры и логины',
                'verbose_name_plural': 'Старые договоры и логины',
            },
        ),
    ]
