# Generated by Django 4.1.7 on 2024-01-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0008_oldlogindogowor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='beneficiary',
            field=models.BooleanField(blank=True, default=False, verbose_name='Льготник'),
        ),
        migrations.AddField(
            model_name='usertablearhiw',
            name='beneficiary',
            field=models.BooleanField(blank=True, default=False, verbose_name='Льготник'),
        ),
    ]
