# Generated by Django 4.1.7 on 2024-02-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0009_usertable_beneficiary_usertablearhiw_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='agent_id',
            field=models.CharField(blank=True, max_length=4, verbose_name='agent_id'),
        ),
    ]
