# Generated by Django 4.1.7 on 2024-02-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0010_zakaz_agent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='priceProc',
        ),
        migrations.RemoveField(
            model_name='zakaz',
            name='total_priceProc',
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='action',
            field=models.CharField(choices=[('', ''), ('бно', 'бно'), ('заказ подтвержден', 'заказ подтвержден')], max_length=32, verbose_name='бно/повторно/потдвержден'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='total_price',
            field=models.CharField(max_length=16, verbose_name='Общая цена с процентом'),
        ),
    ]
