# Generated by Django 4.1.7 on 2024-02-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0011_remove_zakaz_priceproc_remove_zakaz_total_priceproc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NachMonthDebetKredet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edaraOrNasel', models.BooleanField(default=False, verbose_name='Edara')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('month', models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=16, verbose_name='Месяц')),
                ('etrap', models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=32, verbose_name='Этрап')),
                ('number', models.CharField(max_length=32, verbose_name='Номер')),
                ('debet', models.FloatField(default=0, verbose_name='debet')),
                ('kredet', models.FloatField(default=0, verbose_name='kredet')),
            ],
            options={
                'verbose_name': 'Баланс для Дибит, Кредит',
                'verbose_name_plural': 'Баланс для Дибит, Кредит',
            },
        ),
    ]
