# Generated by Django 4.1.7 on 2024-02-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0013_nonlocalcall_edara'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcall',
            name='edara',
            field=models.CharField(blank=True, max_length=16, verbose_name='H, B, или I'),
        ),
    ]
