# Generated by Django 4.1.7 on 2024-02-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0014_localcall_edara'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthPlatejiFromBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=128, verbose_name='Менеджер')),
                ('pay_date', models.DateField(verbose_name='Дата Платежа')),
                ('dogowor', models.CharField(max_length=32, verbose_name='Договор')),
                ('price', models.FloatField(verbose_name='Платеж')),
                ('kod_oplaty', models.CharField(max_length=32, verbose_name='Код оплаты')),
                ('FAO', models.CharField(max_length=256, verbose_name='Ф.И.О')),
            ],
            options={
                'verbose_name': 'Платежи взятые с биллинга',
                'verbose_name_plural': 'Платеж взятые с биллинга',
            },
        ),
    ]
