# Generated by Django 4.1.7 on 2024-02-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0015_monthplatejifrombilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthplatejifrombilling',
            name='date_price',
            field=models.CharField(blank=True, max_length=32, verbose_name='Дата вместо цены'),
        ),
        migrations.AlterField(
            model_name='monthplatejifrombilling',
            name='FAO',
            field=models.CharField(blank=True, max_length=256, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='monthplatejifrombilling',
            name='kod_oplaty',
            field=models.CharField(blank=True, max_length=32, verbose_name='Код оплаты'),
        ),
    ]
