# Generated by Django 4.1.7 on 2024-02-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0016_monthplatejifrombilling_date_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthplatejifrombilling',
            name='YurOrFiz',
            field=models.CharField(blank=True, max_length=32, verbose_name='Юридическое или Физическое лицо'),
        ),
        migrations.AddField(
            model_name='monthplatejifrombilling',
            name='platejiType',
            field=models.CharField(blank=True, max_length=64, verbose_name='Внешние платежи, default или Оплачено по карте'),
        ),
    ]
