# Generated by Django 4.1.7 on 2024-02-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0017_monthplatejifrombilling_yurorfiz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthplatejifrombilling',
            options={'verbose_name': 'Платеж взятые с биллинга', 'verbose_name_plural': 'Платежи взятые с биллинга'},
        ),
    ]
