# Generated by Django 4.1.7 on 2024-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0018_alter_monthplatejifrombilling_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthPlatejiOFFFromBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=128, verbose_name='Менеджер')),
                ('pay_date', models.DateField(verbose_name='Дата Платежа')),
                ('dogowor', models.CharField(max_length=32, verbose_name='Договор')),
                ('price', models.FloatField(verbose_name='Платеж')),
                ('platejiType', models.CharField(blank=True, max_length=64, verbose_name='Внешние платежи, default или Оплачено по карте')),
                ('date_price', models.CharField(blank=True, max_length=32, verbose_name='Дата вместо цены')),
                ('kod_oplaty', models.CharField(blank=True, max_length=32, verbose_name='Код оплаты')),
                ('YurOrFiz', models.CharField(blank=True, max_length=32, verbose_name='Юридическое или Физическое лицо')),
                ('FAO', models.CharField(blank=True, max_length=256, verbose_name='Ф.И.О')),
            ],
            options={
                'verbose_name': 'Платеж OFF взятые с биллинга',
                'verbose_name_plural': 'Платежи OFF взятые с биллинга',
            },
        ),
    ]
