# Generated by Django 4.1.7 on 2024-02-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0019_monthplatejiofffrombilling'),
    ]

    operations = [
        migrations.CreateModel(
            name='SagidDecemberDebetKredet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='Номер')),
                ('debit', models.FloatField(default=0, max_length=32, verbose_name='Дебит')),
                ('kredit', models.FloatField(default=0, max_length=32, verbose_name='Кредит')),
            ],
            options={
                'verbose_name': 'Сагид дебит кредит декабрь 2023',
                'verbose_name_plural': 'Сагид дебит кредит декабрь 2023',
            },
        ),
    ]
