# Generated by Django 4.1.7 on 2024-02-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0020_sagiddecemberdebetkredet'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='intOffDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отключения интернета'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='intOnDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подключения интернета'),
        ),
    ]
