# Generated by Django 4.1.7 on 2024-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0021_usertable_intoffdate_usertable_intondate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatejiWhichAddKassirsEveryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Ф.И.О')),
                ('dogowor', models.CharField(blank=True, max_length=32, verbose_name='Dogowor')),
                ('nomerPlateja', models.CharField(blank=True, max_length=32, verbose_name='Номер платежа')),
                ('price', models.FloatField(verbose_name='Сумма платежа')),
                ('manager', models.CharField(blank=True, max_length=64, verbose_name='Менеджер')),
                ('date', models.DateField(blank=True, verbose_name='Дата платежа')),
                ('datePlatejProweden', models.DateField(blank=True, verbose_name='Дата проведения платежа')),
                ('account', models.CharField(blank=True, max_length=16, verbose_name='Счет №')),
                ('is_cart', models.BooleanField(default=False)),
                ('payPorucheniye', models.CharField(blank=True, max_length=32, verbose_name='Платежное поручение')),
                ('comment', models.CharField(blank=True, max_length=32, verbose_name='Комментарий')),
                ('operator', models.CharField(blank=True, max_length=32, verbose_name='Оператор')),
                ('kodOplaty', models.CharField(blank=True, max_length=32, verbose_name='Код оплаты')),
            ],
            options={
                'verbose_name': 'Сагид дебит кредит декабрь 2023',
                'verbose_name_plural': 'Сагид дебит кредит декабрь 2023',
            },
        ),
    ]
