# Generated by Django 4.1.7 on 2024-02-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0022_platejiwhichaddkassirseveryday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platejiwhichaddkassirseveryday',
            options={'verbose_name': 'Платежи кассиров', 'verbose_name_plural': 'Платежи кассиров'},
        ),
        migrations.AddField(
            model_name='platejiwhichaddkassirseveryday',
            name='etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=32, verbose_name='Этрап'),
        ),
    ]
