# Generated by Django 4.1.7 on 2024-02-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0023_alter_platejiwhichaddkassirseveryday_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platejiwhichaddkassirseveryday',
            options={'verbose_name': 'Платежи c биллинга кассиров', 'verbose_name_plural': 'Платежи c биллинга кассиров'},
        ),
        migrations.AddField(
            model_name='dontrepeatyourself',
            name='platejiSkassyKassirami',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='гггг-мм-дд  Платежи с файла биллинга в нашу кассу кассирами'),
        ),
    ]
