# Generated by Django 4.1.7 on 2024-03-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0024_alter_platejiwhichaddkassirseveryday_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etrap', models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=32, verbose_name='Этрап')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Менеджер')),
            ],
        ),
        migrations.AlterField(
            model_name='staffaction',
            name='action',
            field=models.CharField(choices=[('Delete', 'Delete'), ('Update', 'Update'), ('Recover', 'Recover'), ('Снятие Номера', 'Снятие Номера'), ('Безвозвратное удаление номера', 'Безвозвратное удаление номера'), ('Востановление номера', 'Востановление номера'), ('Начисления СЛР', 'Начисления СЛР'), ('Начисления КОД', 'Начисления КОД'), ('Начисления КОД+СЛР', 'Начисления КОД+СЛР'), ('Начисления Интернет Платежей', 'Начисления Интернет Платежей'), ('Импорт с xlsx внешние платежи в БД', 'Импорт с xlsx внешние платежи в БД'), ('Импорт с xlsx Интернет Начисления в БД', 'Импорт с xlsx Интернет Начисления в БД'), ('Импорт с xlsx Alem Начисления в БД', 'Импорт с xlsx Alem Начисления в БД'), ('Another', 'Another'), ('Начисления Интернет', 'Начисления Интернет'), ('Начисления абонплата', 'Начисления абонплата'), ('Начисления метры', 'Начисления метры'), ('Начисления заказ', 'Начисления заказ'), ('Начисления Доп Услуг', 'Начисления Доп Услуг'), ('Изменение Услуг', 'Изменение Услуг'), ('Подключения/смена интернет тарифа', 'Подключения/смена интернет тарифа'), ('Подключения/смена метров', 'Подключения/смена метров'), ('Кабель TV действия', 'Кабель TV действия'), ('Alem TV действия', 'Alem TV действия'), ('Изменение данных абонента в MATB в базе данных', 'Изменение данных абонента в MATB в базе данных'), ('Добавление абонента в MATB в базе данных', 'Добавление абонента в MATB в базе данных'), ('Перекидка', 'Перекидка'), ('Old Login Dogowor Save', 'Old Login Dogowor Save')], max_length=64),
        ),
    ]
