# Generated by Django 4.1.7 on 2024-03-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0025_managernames_alter_staffaction_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managernames',
            options={'verbose_name': 'Этрап и имена кассиров', 'verbose_name_plural': 'Этрап и имя кассира'},
        ),
        migrations.RenameField(
            model_name='platejiwhichaddkassirseveryday',
            old_name='etrap',
            new_name='kassir_etrap',
        ),
        migrations.AddField(
            model_name='platejiwhichaddkassirseveryday',
            name='type_pay',
            field=models.CharField(blank=True, max_length=256, verbose_name='тип платежа (абонплата, итернет, ...)'),
        ),
        migrations.AddField(
            model_name='platejiwhichaddkassirseveryday',
            name='user_etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=32, verbose_name='Этрап'),
        ),
    ]
