# Generated by Django 4.1.7 on 2024-03-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0026_alter_managernames_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platejiwhichaddkassirseveryday',
            name='account',
        ),
        migrations.RemoveField(
            model_name='platejiwhichaddkassirseveryday',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='platejiwhichaddkassirseveryday',
            name='datePlatejProweden',
        ),
        migrations.RemoveField(
            model_name='platejiwhichaddkassirseveryday',
            name='is_cart',
        ),
        migrations.RemoveField(
            model_name='platejiwhichaddkassirseveryday',
            name='nomerPlateja',
        ),
        migrations.RemoveField(
            model_name='platejiwhichaddkassirseveryday',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='platejiwhichaddkassirseveryday',
            name='payPorucheniye',
        ),
        migrations.AddField(
            model_name='platejiwhichaddkassirseveryday',
            name='is_enterprises',
            field=models.CharField(blank=True, max_length=32, verbose_name='ЮЛ или ФЛ'),
        ),
        migrations.AddField(
            model_name='platejiwhichaddkassirseveryday',
            name='pay_category',
            field=models.CharField(blank=True, max_length=256, verbose_name='Категория платежа (Внешние Платежи, Default или Оплата картой)'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='type_pay',
            field=models.CharField(blank=True, max_length=16, verbose_name='Тип платежа (абонплата, итернет, ...)'),
        ),
    ]
