# Generated by Django 4.1.7 on 2024-03-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0027_remove_platejiwhichaddkassirseveryday_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Тип Внешнего Платежа')),
            ],
            options={
                'verbose_name': 'Типы Внешних Платежей',
                'verbose_name_plural': 'Тип Внешнего Платежа',
            },
        ),
    ]
