# Generated by Django 4.1.7 on 2024-03-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0028_externalpayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managernames',
            name='etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Внешние платежи', 'Внешние платежи')], max_length=32, verbose_name='Этрап'),
        ),
    ]
