# Generated by Django 4.1.7 on 2024-03-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0029_alter_managernames_etrap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalPayments',
        ),
        migrations.AddField(
            model_name='platejiwhichaddkassirseveryday',
            name='file_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='kassir_etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Внешние платежи', 'Внешние платежи')], max_length=32, verbose_name='Этрап кассира'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='user_etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=32, verbose_name='Этрап абонента'),
        ),
    ]
