# Generated by Django 4.1.7 on 2024-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0030_delete_externalpayments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platejiwhichaddkassirseveryday',
            name='when_added_file',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='platejiwhichaddkassirseveryday',
            name='who_add_file',
            field=models.CharField(blank=True, max_length=64, verbose_name='Кто добавил файл'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='file_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Файл'),
        ),
    ]
