# Generated by Django 4.1.7 on 2024-03-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0031_platejiwhichaddkassirseveryday_when_added_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platejiwhichaddkassirseveryday',
            name='file_is_nach',
            field=models.BooleanField(default=False, verbose_name='Платежи с этого файла начислены'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='when_added_file',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда файл добавлен в БД'),
        ),
    ]
