# Generated by Django 4.1.7 on 2024-03-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0033_payhistory_edara_ilat_alter_staffaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='kassir_etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=32, null=True, verbose_name='etrap кассира'),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='type',
            field=models.CharField(blank=True, choices=[(None, 'Внешние платежи или default (кассир)'), ('Внешние платежи', 'Внешние платежи'), ('Default', 'Default')], max_length=128, null=True, verbose_name='Внешние платежи или default (кассир)'),
        ),
    ]
