# Generated by Django 4.1.7 on 2024-03-20 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telekom', '0034_payhistory_kassir_etrap_payhistory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='KassaExcelFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/kassirs_pay_excel/%Y-%m-%d/', verbose_name='Файл')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда файл добавлен в БД')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Соотрудник который добавил file')),
            ],
        ),
    ]
