# Generated by Django 4.1.7 on 2024-04-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0035_kassaexcelfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='KodSumm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('month', models.CharField(max_length=2, verbose_name='Месяц')),
                ('internet', models.FloatField(default=0, verbose_name='Интернет')),
                ('kabel', models.FloatField(default=0, verbose_name='Кабель')),
                ('alem', models.FloatField(default=0, verbose_name='Alem TV')),
                ('telefon', models.FloatField(default=0, verbose_name='Телефон')),
                ('slr', models.FloatField(default=0, verbose_name='СЛР')),
                ('kod', models.FloatField(default=0, verbose_name='Код')),
                ('zakaz', models.FloatField(default=0, verbose_name='Заказ')),
                ('prochee', models.FloatField(default=0, verbose_name='Прочее')),
                ('dop_uslugi', models.FloatField(default=0, verbose_name='Доп услуги')),
            ],
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='type',
            field=models.CharField(blank=True, choices=[(None, 'Внешние платежи или default (кассир)'), ('Внешние платежи', 'Внешние платежи'), ('Default', 'Default')], max_length=128, null=True, verbose_name='Внешние платежи или Default (кассир)'),
        ),
    ]
