# Generated by Django 4.1.7 on 2024-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0036_kodsumm_alter_payhistory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Название Группы')),
            ],
            options={
                'verbose_name': 'Экзаменационные группы вопросов',
                'verbose_name_plural': 'Экзаменационная группа вопроса',
            },
        ),
        migrations.CreateModel(
            name='ExamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('Scores_id', models.CharField(max_length=16, verbose_name='Баллы ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer1', models.TextField(verbose_name='Ответ 1')),
                ('answer2', models.TextField(verbose_name='Ответ 2')),
                ('answer3', models.TextField(verbose_name='Ответ 3')),
                ('choised_answer', models.IntegerField(verbose_name='Выбрал ответ №')),
                ('currect_answer', models.IntegerField(verbose_name='Правильный вариант')),
                ('is_currect_answer', models.BooleanField(verbose_name='Ответил правильно?')),
            ],
            options={
                'verbose_name': 'Экзаменационные истории',
                'verbose_name_plural': 'Экзаменационная история',
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('sotowyy', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('q_lang', models.CharField(blank=True, choices=[(None, '----'), ('Туркменский', 'Туркменский'), ('Русский', 'Русский')], max_length=32, verbose_name='Язык вопросов')),
                ('questions_count', models.IntegerField(default=0, verbose_name='Всего количество вопросов')),
                ('currect_answer', models.IntegerField(default=0, verbose_name='Количество правильных ответов')),
                ('error_answer', models.IntegerField(default=0, verbose_name='Количество не правильных ответов')),
                ('scores', models.IntegerField(blank=True, null=True, verbose_name='Баллы')),
                ('start_time', models.DateTimeField(null=True, verbose_name='дата и врема начало экзамена')),
                ('date_of_passing', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи теста')),
                ('duration', models.TimeField(null=True, verbose_name='Длительность сдачи экзамена')),
                ('etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап')),
            ],
            options={
                'verbose_name': 'Экзаменационные баллы',
                'verbose_name_plural': 'Экзаменационный балл',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer1', models.TextField(verbose_name='Ответ 1')),
                ('answer2', models.TextField(verbose_name='Ответ 2')),
                ('answer3', models.TextField(verbose_name='Ответ 3')),
                ('currect_answer', models.CharField(choices=[(None, '----'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, verbose_name='Правильный ответ №: ')),
                ('lang', models.CharField(blank=True, choices=[(None, '----'), ('Туркменский', 'Туркменский'), ('Русский', 'Русский')], max_length=16, verbose_name='Язык вопросов')),
                ('group', models.ManyToManyField(to='telekom.examgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Экзаменационные вопросы',
                'verbose_name_plural': 'Экзаменационный вопрос',
            },
        ),
    ]
