# Generated by Django 4.1.7 on 2024-06-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0037_examgroup_examhistory_scores_examquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='KabelTvNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('street', models.CharField(blank=True, max_length=40, verbose_name='Улица')),
                ('home', models.CharField(blank=True, max_length=40, verbose_name='Дом')),
                ('flat', models.CharField(blank=True, max_length=40, verbose_name='Квартира')),
                ('sotowyy', models.CharField(blank=True, max_length=40, verbose_name='Сотовый номер')),
                ('is_enterprises', models.BooleanField(default=False, verbose_name='Предприятия')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('balance', models.FloatField(default=0, verbose_name='Баланс')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во точек')),
                ('user_add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления пользователя')),
            ],
            options={
                'verbose_name': 'Кабель TV новая база',
                'verbose_name_plural': 'Кабель TV новая база',
            },
        ),
        migrations.CreateModel(
            name='KabelTvPayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.FloatField(default=0, verbose_name='Платеж')),
                ('pay_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('pay_kassir', models.CharField(blank=True, max_length=100, verbose_name='Платеж принял кассир')),
                ('card', models.BooleanField(default=False, verbose_name='Платеж корточкой?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telekom.kabeltvnew', verbose_name='Абонент')),
            ],
            options={
                'verbose_name': 'Исторя платежей Кабель TV',
                'verbose_name_plural': 'Исторя платежей Кабель TV',
            },
        ),
        migrations.CreateModel(
            name='KabelNach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('month', models.CharField(max_length=2, verbose_name='Месяц')),
                ('nach', models.FloatField(default=0, verbose_name='Начисления Сумма')),
                ('nach_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения начисления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telekom.kabeltvnew', verbose_name='Абонент')),
            ],
            options={
                'verbose_name': 'Начисления Кабель TV',
                'verbose_name_plural': 'Начисления Кабель TV',
            },
        ),
        migrations.CreateModel(
            name='KabelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('comment_add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления комментария')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telekom.kabeltvnew', verbose_name='Абонент')),
            ],
            options={
                'verbose_name': 'Комментарии абонентов для Кабель TV новая база',
                'verbose_name_plural': 'Комментарии абонентов для Кабель TV новая база',
            },
        ),
    ]
