# Generated by Django 4.1.7 on 2024-06-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0038_kabeltvnew_kabeltvpayhistory_kabelnach_kabelcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='KabelTVStaffAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(max_length=150, verbose_name='Работник')),
                ('comment', models.CharField(max_length=150, verbose_name='Комментарий соотрудника')),
                ('action', models.TextField(verbose_name='Действие')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения действия')),
            ],
            options={
                'verbose_name': 'История действий персонала для Кабель TV',
                'verbose_name_plural': 'История действий персонала для Кабель TV',
            },
        ),
    ]
