# Generated by Django 4.1.7 on 2024-06-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0039_kabeltvstaffaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KabelTVStaffAction',
        ),
        migrations.AddField(
            model_name='kabelcomment',
            name='action',
            field=models.CharField(choices=[('Изменения данных', 'Изменения данных'), ('Добавление абонента', 'Добавление абонента'), ('Удаление абонента', 'Удаление абонента')], default='Изменения данных', max_length=50, verbose_name='Действие'),
        ),
        migrations.AddField(
            model_name='kabelcomment',
            name='worker',
            field=models.CharField(default=1, max_length=150, verbose_name='Работник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kabelcomment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
