# Generated by Django 4.1.7 on 2024-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0040_delete_kabeltvstaffaction_kabelcomment_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabelcomment',
            name='action',
            field=models.CharField(choices=[('Изменения данных', 'Изменения данных'), ('Добавление абонента', 'Добавление абонента'), ('Удаление абонента', 'Удаление абонента')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='kabeltvnew',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер'),
        ),
    ]
