# Generated by Django 4.1.7 on 2024-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0041_alter_kabelcomment_action_alter_kabeltvnew_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabeltvpayhistory',
            name='pay_date',
            field=models.DateTimeField(verbose_name='Дата платежа'),
        ),
    ]
