# Generated by Django 4.1.7 on 2024-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0042_alter_kabeltvpayhistory_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='managernames',
            name='name2',
            field=models.CharField(blank=True, max_length=256, verbose_name='Логин Менеджера'),
        ),
    ]
