# Generated by Django 4.1.7 on 2024-07-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0043_managernames_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='KabelTvNewDebitKredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('month', models.CharField(max_length=2, verbose_name='Месяц')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('last_DT', models.IntegerField(default=0, verbose_name='Предыдущее Debit')),
                ('last_KT', models.IntegerField(default=0, verbose_name='Предыдущее Kredit')),
                ('nach', models.IntegerField(default=0, verbose_name='Начислено')),
                ('is_enterprises', models.BooleanField(default=False, verbose_name='Предприятия')),
                ('current_DT', models.IntegerField(default=0, verbose_name='Текущий Debit')),
                ('current_KT', models.IntegerField(default=0, verbose_name='Текущий Kredit')),
            ],
            options={
                'verbose_name': 'КабельTVNew DT KT',
                'verbose_name_plural': 'КабельTVNew DT KT',
            },
        ),
        migrations.AlterModelOptions(
            name='kabelcomment',
            options={'verbose_name': 'КабельTVNew Комментарии', 'verbose_name_plural': 'КабельTVNew Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='kabelnach',
            options={'verbose_name': 'КабельTVNew Начисления', 'verbose_name_plural': 'КабельTVNew Начисления'},
        ),
        migrations.AlterModelOptions(
            name='kabeltvnew',
            options={'verbose_name': 'КабельTVNew новая база', 'verbose_name_plural': 'КабельTVNew новая база'},
        ),
        migrations.AlterModelOptions(
            name='kabeltvpayhistory',
            options={'verbose_name': 'КабельTVNew Исторя платежей', 'verbose_name_plural': 'КабельTVNew Исторя платежей'},
        ),
        migrations.CreateModel(
            name='PayAndPayTypeForDebitKredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.IntegerField(default=0, verbose_name='Оплачено')),
                ('pay_type', models.CharField(max_length=124, verbose_name='Тип платежа (с кассы, TOLEG APP TMCELL, e-gov, и.т.п)')),
                ('KabelTvNewDebitKredit_pk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telekom.kabeltvnewdebitkredit', verbose_name='DT KT id (ForeignKey)')),
            ],
            options={
                'verbose_name': 'КабельTVNew Pays for DT KT',
                'verbose_name_plural': 'КабельTVNew Pays for DT KT',
            },
        ),
    ]
