# Generated by Django 4.1.7 on 2024-07-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0044_kabeltvnewdebitkredit_alter_kabelcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabeltvnewdebitkredit',
            name='perekidka_nach',
            field=models.IntegerField(default=0, verbose_name='Акт перекидки начислено'),
        ),
    ]
