# Generated by Django 4.1.7 on 2024-08-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0045_kabeltvnewdebitkredit_perekidka_nach'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Название Предприятия')),
                ('account', models.IntegerField(default=0, verbose_name='Счет номер')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Едара, счет, баланс',
                'verbose_name_plural': 'Едара, счет, баланс',
            },
        ),
    ]
