# Generated by Django 4.1.7 on 2024-08-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0046_accountbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название Предприятия'),
        ),
    ]
