# Generated by Django 4.1.7 on 2024-12-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0047_alter_accountbalance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NachislitWruchnuyuHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='Работник который начислил')),
                ('date', models.DateTimeField(verbose_name='Дата начисления')),
                ('column', models.CharField(max_length=128, verbose_name='Начислил на')),
                ('price', models.FloatField(verbose_name='Начисления на сумму')),
                ('number', models.IntegerField(verbose_name='Номер абонента')),
                ('etrap', models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=32, verbose_name='Этрап абонента')),
            ],
            options={
                'verbose_name': 'Начисления вручную история',
                'verbose_name_plural': 'Начисления вручную история',
            },
        ),
        migrations.AlterField(
            model_name='staffaction',
            name='action',
            field=models.CharField(choices=[('Delete', 'Delete'), ('Update', 'Update'), ('Recover', 'Recover'), ('Снятие Номера', 'Снятие Номера'), ('Безвозвратное удаление номера', 'Безвозвратное удаление номера'), ('Востановление номера', 'Востановление номера'), ('Начисления СЛР', 'Начисления СЛР'), ('Начисления КОД', 'Начисления КОД'), ('Начисления КОД+СЛР', 'Начисления КОД+СЛР'), ('Начисления Интернет Платежей', 'Начисления Интернет Платежей'), ('Импорт с xlsx внешние платежи в БД', 'Импорт с xlsx внешние платежи в БД'), ('Импорт с xlsx Интернет Начисления в БД', 'Импорт с xlsx Интернет Начисления в БД'), ('Импорт с xlsx Alem Начисления в БД', 'Импорт с xlsx Alem Начисления в БД'), ('Another', 'Another'), ('Начисления Интернет', 'Начисления Интернет'), ('Начисления абонплата', 'Начисления абонплата'), ('Начисления метры', 'Начисления метры'), ('Начисления заказ', 'Начисления заказ'), ('Начисления Доп Услуг', 'Начисления Доп Услуг'), ('Изменение Услуг', 'Изменение Услуг'), ('Подключения/смена интернет тарифа', 'Подключения/смена интернет тарифа'), ('Подключения/смена метров', 'Подключения/смена метров'), ('Кабель TV действия', 'Кабель TV действия'), ('Alem TV действия', 'Alem TV действия'), ('Изменение данных абонента в MATB в базе данных', 'Изменение данных абонента в MATB в базе данных'), ('Добавление абонента в MATB в базе данных', 'Добавление абонента в MATB в базе данных'), ('Перекидка', 'Перекидка'), ('Old Login Dogowor Save', 'Old Login Dogowor Save'), ('Добавления платежей в базу', 'Добавления платежей в базу'), ('Пробитие платежей с базы данных', 'Пробитие платежей с базы данных'), ('Ручное начисление', 'Ручное начисление')], max_length=64),
        ),
    ]
