# Generated by Django 4.1.7 on 2024-12-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0048_nachislitwruchnuyuhistory_alter_staffaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachislitwruchnuyuhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления'),
        ),
    ]
