# Generated by Django 4.1.7 on 2024-12-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0049_alter_nachislitwruchnuyuhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachislitwruchnuyuhistory',
            name='comment',
            field=models.CharField(blank=True, max_length=256, verbose_name='Комментарий'),
        ),
    ]
