# Generated by Django 4.1.7 on 2024-12-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0050_nachislitwruchnuyuhistory_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachminus',
            name='hb',
            field=models.CharField(blank=True, max_length=4, verbose_name='Хоз или Бюд'),
        ),
        migrations.AddField(
            model_name='nachminus',
            name='is_enterprises',
            field=models.BooleanField(default=False, verbose_name='Эдара?'),
        ),
    ]
