# Generated by Django 4.1.7 on 2024-12-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0051_nachminus_hb_nachminus_is_enterprises'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerekidkaInfoNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1Number', models.CharField(max_length=64, verbose_name='Номер абонента 1')),
                ('user1Etrap', models.CharField(max_length=64, verbose_name='Этрап абонента 1')),
                ('user1NameSurname', models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия и имя во время перекидки абонента 1')),
                ('user2Number', models.CharField(max_length=64, verbose_name='Номер абонента 2')),
                ('user2Etrap', models.CharField(max_length=64, verbose_name='Этрап абонента 2')),
                ('user2NameSurname', models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия и имя во время перекидки абонента 2')),
                ('operator', models.CharField(max_length=256, verbose_name='Кто делал перекидку')),
                ('comment', models.CharField(max_length=512, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время перекидки')),
                ('type_perekidka', models.CharField(max_length=64, verbose_name='Полная перекидка или перекидка баланса')),
                ('internet1', models.FloatField(default=0, verbose_name='Перекинуто с Интернет')),
                ('kabel1', models.FloatField(default=0, verbose_name=' Перекинуто с Кабель')),
                ('alem1', models.FloatField(default=0, verbose_name=' Перекинуто с Alem TV')),
                ('telefon1', models.FloatField(default=0, verbose_name='Перекинуто с Телефон')),
                ('internet2', models.FloatField(default=0, verbose_name='Перекинуто на Интернет')),
                ('kabel2', models.FloatField(default=0, verbose_name=' Перекинуто на Кабель')),
                ('alem2', models.FloatField(default=0, verbose_name=' Перекинуто на Alem TV')),
                ('telefon2', models.FloatField(default=0, verbose_name='Перекинуто на Телефон')),
            ],
            options={
                'verbose_name': 'Информация о перекидках New',
                'verbose_name_plural': 'Информация о перекидках New',
            },
        ),
    ]
