# Generated by Django 4.1.7 on 2024-12-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0052_perekidkainfonew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='alem2',
            field=models.FloatField(default=0, verbose_name=' Получено на Alem TV'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='comment',
            field=models.CharField(blank=True, max_length=512, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='internet2',
            field=models.FloatField(default=0, verbose_name='Получено на Интернет'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='kabel2',
            field=models.FloatField(default=0, verbose_name=' Получено на Кабель'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='operator',
            field=models.CharField(blank=True, max_length=256, verbose_name='Кто делал перекидку'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='telefon2',
            field=models.FloatField(default=0, verbose_name='Получено на Телефон'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='type_perekidka',
            field=models.CharField(blank=True, max_length=64, verbose_name='"полная перекидка" или "перекидка баланса"'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user1Etrap',
            field=models.CharField(blank=True, max_length=64, verbose_name='Этрап абонента 1'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user1Number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер абонента 1'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user2Etrap',
            field=models.CharField(blank=True, max_length=64, verbose_name='Этрап абонента 2'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user2Number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер абонента 2'),
        ),
    ]
