# Generated by Django 4.1.7 on 2024-12-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0053_alter_perekidkainfonew_alem2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2KabelEtrap',
            field=models.CharField(blank=True, max_length=64, verbose_name='Этрап kabel абонента 2'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2KabelNameSurname',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия и имя во время перекидки kabel абонента 2'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2KabelNumber',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер kabel абонента 2'),
        ),
    ]
