# Generated by Django 4.1.7 on 2024-12-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0054_perekidkainfonew_user2kabeletrap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perekidkainfonew',
            name='user2KabelEtrap',
        ),
    ]
