# Generated by Django 4.1.7 on 2024-12-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0055_remove_perekidkainfonew_user2kabeletrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perekidkainfonew',
            name='alem1',
        ),
        migrations.RemoveField(
            model_name='perekidkainfonew',
            name='alem2',
        ),
        migrations.RemoveField(
            model_name='perekidkainfonew',
            name='internet1',
        ),
        migrations.RemoveField(
            model_name='perekidkainfonew',
            name='internet2',
        ),
        migrations.RemoveField(
            model_name='perekidkainfonew',
            name='kabel1',
        ),
        migrations.RemoveField(
            model_name='perekidkainfonew',
            name='kabel2',
        ),
        migrations.RemoveField(
            model_name='perekidkainfonew',
            name='telefon1',
        ),
        migrations.RemoveField(
            model_name='perekidkainfonew',
            name='telefon2',
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2KabelEtrap',
            field=models.CharField(blank=True, max_length=64, verbose_name='Этрап kabel абонента 2'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
