# Generated by Django 4.1.7 on 2024-12-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0056_remove_perekidkainfonew_alem1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perekidkainfonew',
            name='alem1',
            field=models.FloatField(default=0, verbose_name=' Перекинуто с Alem TV'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='alem2',
            field=models.FloatField(default=0, verbose_name=' Получено на Alem TV'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='internet1',
            field=models.FloatField(default=0, verbose_name='Перекинуто с Интернет'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='internet2',
            field=models.FloatField(default=0, verbose_name='Получено на Интернет'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='kabel1',
            field=models.FloatField(default=0, verbose_name=' Перекинуто с Кабель'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='kabel2',
            field=models.FloatField(default=0, verbose_name=' Получено на Кабель'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='telefon1',
            field=models.FloatField(default=0, verbose_name='Перекинуто с Телефон'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='telefon2',
            field=models.FloatField(default=0, verbose_name='Получено на Телефон'),
        ),
    ]
