# Generated by Django 4.1.7 on 2024-12-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0057_perekidkainfonew_alem1_perekidkainfonew_alem2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perekidkainfonew',
            name='user2KabelEtrap',
        ),
    ]
