# Generated by Django 4.1.7 on 2024-12-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0058_remove_perekidkainfonew_user2kabeletrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1KabelNameSurname',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Фамилия и имя во время перекидки kabel абонента 1'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1KabelNumber',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер kabel абонента 1'),
        ),
    ]
