# Generated by Django 4.1.7 on 2024-12-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0059_perekidkainfonew_user1kabelnamesurname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnyatieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=8, verbose_name='Номер')),
                ('etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап')),
                ('operator_galochka', models.CharField(blank=True, max_length=256, verbose_name='Кто ставил галочку')),
                ('date_galochka', models.DateTimeField(blank=True, null=True, verbose_name='Дата галочки')),
                ('namesurname1', models.CharField(blank=True, max_length=512, null=True, verbose_name='Абонент при галочки')),
                ('operator_snyal', models.CharField(blank=True, max_length=256, verbose_name='Кто снял абонента')),
                ('date_snyal', models.DateTimeField(blank=True, null=True, verbose_name='Дата снятия')),
                ('namesurname2', models.CharField(blank=True, max_length=512, null=True, verbose_name='Абонент при снятии')),
                ('comment_galochka', models.TextField(blank=True, null=True, verbose_name='Комментарий при галочки')),
            ],
            options={
                'verbose_name': 'Информация о снятиях New',
                'verbose_name_plural': 'Информация о снятиях New',
            },
        ),
    ]
