# Generated by Django 4.1.7 on 2024-12-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0060_snyatieinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UstanowkaSnyatieDopUslugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='Кто выполнил')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('which_action', models.CharField(max_length=128, verbose_name='изменения при')),
                ('which_type', models.CharField(max_length=128, verbose_name='установлено/снято')),
                ('number', models.IntegerField(verbose_name='Номер абонента')),
                ('etrap', models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=32, verbose_name='Этрап абонента')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Информация об установленных и снятых услуг',
                'verbose_name_plural': 'Информация об установленных и снятых услуг',
            },
        ),
    ]
