# Generated by Django 4.1.7 on 2024-12-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0061_ustanowkasnyatiedopuslughistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPaysWithKassirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап')),
                ('checked_date', models.CharField(blank=True, max_length=16, verbose_name='Какой день сверил')),
                ('operator', models.CharField(blank=True, max_length=256, verbose_name='Кто Проверил')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Когда проверил')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Информация о сверках платежей',
                'verbose_name_plural': 'Информация о сверках платежей',
            },
        ),
    ]
