# Generated by Django 4.1.7 on 2024-12-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0062_checkpayswithkassirs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoBalancePoGodam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап')),
                ('number', models.CharField(blank=True, max_length=8, verbose_name='Номер')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год')),
                ('b_internet', models.FloatField(default=0, verbose_name=' Баланс Интернет')),
                ('b_kabel', models.FloatField(default=0, verbose_name=' Баланс Кабель')),
                ('b_alem', models.FloatField(default=0, verbose_name=' Баланс Alem TV')),
                ('b_telefon', models.FloatField(default=0, verbose_name='Баланс Телефон')),
                ('b_slr', models.FloatField(default=0, verbose_name='Баланс СЛР')),
                ('b_kod', models.FloatField(default=0, verbose_name='Баланс Код')),
                ('b_zakaz', models.FloatField(default=0, verbose_name='Баланс Заказ')),
                ('b_prochee', models.FloatField(default=0, verbose_name='Баланс Прочее')),
                ('b_dop_uslugi', models.FloatField(default=0, verbose_name='Баланс Доп. Услуги')),
                ('s_internet', models.FloatField(default=0, verbose_name=' Сальдо Интернет')),
                ('s_kabel', models.FloatField(default=0, verbose_name=' Сальдо Кабель')),
                ('s_alem', models.FloatField(default=0, verbose_name=' Сальдо Alem TV')),
                ('s_telefon', models.FloatField(default=0, verbose_name='Сальдо Телефон')),
                ('s_slr', models.FloatField(default=0, verbose_name='Сальдо СЛР')),
                ('s_kod', models.FloatField(default=0, verbose_name='Сальдо Код')),
                ('s_zakaz', models.FloatField(default=0, verbose_name='Сальдо Заказ')),
                ('s_prochee', models.FloatField(default=0, verbose_name='Сальдо Прочее')),
                ('s_dop_uslugi', models.FloatField(default=0, verbose_name='Сальдо Доп. Услуги')),
            ],
            options={
                'verbose_name': 'Информация о балансе и сальдо по годам',
                'verbose_name_plural': 'Информация о балансе и сальдо по годам',
            },
        ),
    ]
