# Generated by Django 4.1.7 on 2024-12-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0063_saldobalancepogodam'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazaChangeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап')),
                ('number', models.CharField(blank=True, max_length=8, verbose_name='Номер')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('operator', models.CharField(blank=True, max_length=256, verbose_name='Кто изменил')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата изменения')),
                ('akt_raport', models.CharField(blank=True, max_length=256, verbose_name='Акт рапорт')),
            ],
            options={
                'verbose_name': 'Информация об изменениях в База',
                'verbose_name_plural': 'Информация об изменениях в База',
            },
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='flat',
            field=models.CharField(blank=True, max_length=40, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='home',
            field=models.CharField(blank=True, max_length=40, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Имя/Отдел'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='street',
            field=models.CharField(blank=True, max_length=40, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='surname',
            field=models.CharField(blank=True, max_length=40, verbose_name='Фамилия/организация'),
        ),
    ]
