# Generated by Django 4.1.7 on 2025-01-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0064_bazachangeinfo_saldobalancepogodam_flat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NachPerekidkaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1Number', models.CharField(blank=True, max_length=64, verbose_name='Номер абонента 1')),
                ('user1Etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап абонента 1')),
                ('user2Number', models.CharField(blank=True, max_length=64, verbose_name='Номер абонента 2')),
                ('user2Etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап абонента 2')),
                ('operator', models.CharField(blank=True, max_length=256, verbose_name='Кто делал перекидку')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время перекидки')),
                ('internet1', models.FloatField(default=0, verbose_name='Перекинуто с Интернет')),
                ('kabel1', models.FloatField(default=0, verbose_name=' Перекинуто с Кабель')),
                ('alem1', models.FloatField(default=0, verbose_name=' Перекинуто с Alem TV')),
                ('telefon1', models.FloatField(default=0, verbose_name='Перекинуто с Телефон')),
                ('slr1', models.FloatField(default=0, verbose_name='Перекинуто с слр')),
                ('kod1', models.FloatField(default=0, verbose_name='Перекинуто с код')),
                ('zakaz1', models.FloatField(default=0, verbose_name='Перекинуто с заказ')),
                ('prochee1', models.FloatField(default=0, verbose_name='Перекинуто с прочее')),
                ('dop_uslugi1', models.FloatField(default=0, verbose_name='Перекинуто с доп услуги')),
                ('internet2', models.FloatField(default=0, verbose_name='Получено на Интернет')),
                ('kabel2', models.FloatField(default=0, verbose_name=' Получено на Кабель')),
                ('alem2', models.FloatField(default=0, verbose_name=' Получено на Alem TV')),
                ('telefon2', models.FloatField(default=0, verbose_name='Получено на Телефон')),
                ('slr2', models.FloatField(default=0, verbose_name='Перекинуто на слр')),
                ('kod2', models.FloatField(default=0, verbose_name='Перекинуто на код')),
                ('zakaz2', models.FloatField(default=0, verbose_name='Перекинуто на заказ')),
                ('prochee2', models.FloatField(default=0, verbose_name='Перекинуто на прочее')),
                ('dop_uslugi2', models.FloatField(default=0, verbose_name='Перекинуто на доп услуги')),
            ],
            options={
                'verbose_name': 'Информация о перекидках начислений New',
                'verbose_name_plural': 'Информация о перекидках начислений New',
            },
        ),
    ]
