# Generated by Django 4.1.7 on 2025-01-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0065_nachperekidkahistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='abonplata',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Абонплата'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='flat_k',
            field=models.CharField(blank=True, max_length=40, verbose_name='Квартира Кабельное'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='home_k',
            field=models.CharField(blank=True, max_length=40, verbose_name='Дом Кабельное'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='kabel_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во точек'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='name_k',
            field=models.CharField(blank=True, max_length=40, verbose_name='Имя/Отдел Кабельное'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='service',
            field=models.ManyToManyField(blank=True, to='telekom.abonentservice', verbose_name='Доп.Услуги (добавлять через ctrl)'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='street_k',
            field=models.CharField(blank=True, max_length=40, verbose_name='Улица Кабельное'),
        ),
        migrations.AddField(
            model_name='saldobalancepogodam',
            name='surnam_k',
            field=models.CharField(blank=True, max_length=40, verbose_name='Фамилия/организация Кабельное'),
        ),
    ]
