# Generated by Django 4.1.7 on 2025-01-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0066_saldobalancepogodam_abonplata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldobalancepogodam',
            old_name='surnam_k',
            new_name='surname_k',
        ),
    ]
