# Generated by Django 4.1.7 on 2025-01-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0067_rename_surnam_k_saldobalancepogodam_surname_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldlogindogowor',
            name='hb',
            field=models.CharField(blank=True, max_length=2, verbose_name='H или B'),
        ),
        migrations.AddField(
            model_name='oldlogindogowor',
            name='is_enterprises',
            field=models.BooleanField(blank=True, default=False, verbose_name='Предприятия'),
        ),
        migrations.AddField(
            model_name='oldlogindogowor',
            name='operator',
            field=models.CharField(blank=True, max_length=256, verbose_name='Кто сохранял в old'),
        ),
        migrations.AddField(
            model_name='oldlogindogowor',
            name='saved_in_action',
            field=models.CharField(blank=True, max_length=256, verbose_name='Сохранено при действии'),
        ),
    ]
