# Generated by Django 4.1.7 on 2025-01-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0068_oldlogindogowor_hb_oldlogindogowor_is_enterprises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='checked_kassir',
            field=models.CharField(blank=True, max_length=64, verbose_name='Проверенный кассир'),
        ),
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='day_is_closed',
            field=models.BooleanField(default=False, verbose_name='День Закрыт'),
        ),
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='who_close_the_day',
            field=models.CharField(blank=True, max_length=64, verbose_name='Кто закрыл день'),
        ),
    ]
