# Generated by Django 4.1.7 on 2025-01-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0069_checkpayswithkassirs_checked_kassir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveInfoAboutWhoAddAndNachPaysFromBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=500, verbose_name='Название файла')),
                ('etrap_add', models.CharField(blank=True, max_length=64, verbose_name='Этрап добавил')),
                ('who_add', models.CharField(blank=True, max_length=128, verbose_name='Кто добавил')),
                ('when_add', models.DateTimeField(verbose_name='Когда добавил')),
                ('etrap_nach', models.CharField(blank=True, max_length=64, verbose_name='Этрап начислили')),
                ('who_nach', models.CharField(blank=True, max_length=128, verbose_name='Кто начислил')),
                ('when_nach', models.DateTimeField(blank=True, null=True, verbose_name='Когда начислил')),
            ],
            options={
                'verbose_name': 'Информация о том кто добавил и начислил платеж с LanBillinga',
                'verbose_name_plural': 'Информация о том кто добавил и начислил платеж с LanBillinga',
            },
        ),
    ]
