# Generated by Django 4.1.7 on 2025-01-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0070_saveinfoaboutwhoaddandnachpaysfrombilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='itogo_kassir',
            field=models.FloatField(default=0, verbose_name='itogo для этого кассира'),
        ),
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='itogo_when_closed_day',
            field=models.FloatField(default=0, verbose_name='итого за весь день (при закрытии дня)'),
        ),
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='total_alem',
            field=models.FloatField(default=0, verbose_name='сумма Alem'),
        ),
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='total_alem_when_closed_day',
            field=models.FloatField(default=0, verbose_name='сумма Alem за весь день (при закрытии дня)'),
        ),
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='total_internet',
            field=models.FloatField(default=0, verbose_name='сумма интернет'),
        ),
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='total_internet_when_closed_day',
            field=models.FloatField(default=0, verbose_name='сумма интернет за весь день (при закрытии дня)'),
        ),
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='total_kabel',
            field=models.FloatField(default=0, verbose_name='сумма кабель'),
        ),
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='total_kabel_when_closed_day',
            field=models.FloatField(default=0, verbose_name='сумма кабель за весь день (при закрытии дня)'),
        ),
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='total_telefon',
            field=models.FloatField(default=0, verbose_name='сумма телефонии'),
        ),
        migrations.AddField(
            model_name='checkpayswithkassirs',
            name='total_telefon_when_closed_day',
            field=models.FloatField(default=0, verbose_name='сумма телефонии за весь день (при закрытии дня)'),
        ),
    ]
