# Generated by Django 4.1.7 on 2025-02-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0071_checkpayswithkassirs_itogo_kassir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveinfoaboutwhoaddandnachpaysfrombilling',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий по поводу удаления'),
        ),
        migrations.AddField(
            model_name='saveinfoaboutwhoaddandnachpaysfrombilling',
            name='date_delete',
            field=models.CharField(blank=True, max_length=64, verbose_name='Дата платежей для удаления'),
        ),
        migrations.AddField(
            model_name='saveinfoaboutwhoaddandnachpaysfrombilling',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AddField(
            model_name='saveinfoaboutwhoaddandnachpaysfrombilling',
            name='manager',
            field=models.CharField(blank=True, max_length=500, verbose_name='manager платежей для удаления'),
        ),
        migrations.AddField(
            model_name='saveinfoaboutwhoaddandnachpaysfrombilling',
            name='when_delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда удалил'),
        ),
    ]
