# Generated by Django 4.1.7 on 2025-03-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0072_saveinfoaboutwhoaddandnachpaysfrombilling_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabelcomment',
            name='perekidka_info_new_pk',
            field=models.IntegerField(default=0, verbose_name='id perekidka_info_new для быстрого поиска и отмены (востановления)'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1Kbalance',
            field=models.FloatField(default=0, verbose_name='(Кабель1) Баланс'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1Kcount',
            field=models.IntegerField(default=0, verbose_name='(Кабель1) Кол-во точек'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1Kflat',
            field=models.CharField(blank=True, max_length=40, verbose_name='(Кабель1) Квартира'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1Khome',
            field=models.CharField(blank=True, max_length=40, verbose_name='(Кабель1) Дом'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1Kis_active',
            field=models.BooleanField(default=False, verbose_name='(Кабель1) Активный'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1Kis_enterprises',
            field=models.BooleanField(default=False, verbose_name='(Кабель1) Предприятия'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1Kname',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Кабель1) Имя'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1Ksotowyy',
            field=models.CharField(blank=True, max_length=40, verbose_name='(Кабель1) Сотовый номер'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1Kstreet',
            field=models.CharField(blank=True, max_length=40, verbose_name='(Кабель1) Улица'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user1Ksurname',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Кабель1) Фамилия'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2Kbalance',
            field=models.FloatField(default=0, verbose_name='(Кабель2) Баланс'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2Kcount',
            field=models.IntegerField(default=0, verbose_name='(Кабель2) Кол-во точек'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2Kflat',
            field=models.CharField(blank=True, max_length=40, verbose_name='(Кабель2) Квартира'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2Khome',
            field=models.CharField(blank=True, max_length=40, verbose_name='(Кабель2) Дом'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2Kis_active',
            field=models.BooleanField(default=False, verbose_name='(Кабель2) Активный'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2Kis_enterprises',
            field=models.BooleanField(default=False, verbose_name='(Кабель2) Предприятия'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2Kname',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Кабель2) Имя'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2Ksotowyy',
            field=models.CharField(blank=True, max_length=40, verbose_name='(Кабель2) Сотовый номер'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2Kstreet',
            field=models.CharField(blank=True, max_length=40, verbose_name='(Кабель2) Улица'),
        ),
        migrations.AddField(
            model_name='perekidkainfonew',
            name='user2Ksurname',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Кабель2) Фамилия'),
        ),
        migrations.AddField(
            model_name='staffaction',
            name='perekidka_info_new_pk',
            field=models.IntegerField(default=0, verbose_name='id perekidka_info_new для быстрого поиска и отмены (востановления)'),
        ),
        migrations.AddField(
            model_name='usertablearhiw',
            name='perekidka_info_new_pk',
            field=models.IntegerField(default=0, verbose_name='id perekidka_info_new для быстрого поиска и отмены (востановления)'),
        ),
        migrations.AddField(
            model_name='ustanowkasnyatiedopuslughistory',
            name='perekidka_info_new_pk',
            field=models.IntegerField(default=0, verbose_name='id perekidka_info_new для быстрого поиска и отмены (востановления)'),
        ),
    ]
