# Generated by Django 4.1.7 on 2025-03-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0073_kabelcomment_perekidka_info_new_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldlogindogowor',
            name='account',
            field=models.IntegerField(blank=True, null=True, verbose_name='Счет №'),
        ),
    ]
