# Generated by Django 5.1.7 on 2025-04-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0075_alter_staffaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название Предприятия'),
        ),
        migrations.AlterField(
            model_name='accountname',
            name='account',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='accountname',
            name='accountAdress',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес счет №'),
        ),
        migrations.AlterField(
            model_name='accountname',
            name='accountName',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя счет №'),
        ),
        migrations.AlterField(
            model_name='bazachangeinfo',
            name='akt_raport',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Акт рапорт'),
        ),
        migrations.AlterField(
            model_name='bazachangeinfo',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='bazachangeinfo',
            name='operator',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='checkpayswithkassirs',
            name='checked_kassir',
            field=models.CharField(blank=True, max_length=500, verbose_name='Проверенный кассир'),
        ),
        migrations.AlterField(
            model_name='checkpayswithkassirs',
            name='operator',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кто Проверил'),
        ),
        migrations.AlterField(
            model_name='checkpayswithkassirs',
            name='who_close_the_day',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кто закрыл день'),
        ),
        migrations.AlterField(
            model_name='dbfnamelist',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Названия DBF файла'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='KabelNachisleniaYearMonthEtrap',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Начисленный Год, Месяц и этрап для Kabel TV'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='abonplataNachisleniaYearMonthEtrap',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Начисленный Год, Месяц и этрап для Абонплата'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='alemNachisleniyaXlsxName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Добавленный xlsx файл имени alem начисления в нашу БД'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='alemNachisleniyaYearMonthEtrapONOFF',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Начисленный Год, Месяц, Этрап  и ON/OFF Alem начисления'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='dopUslugiNachisleniyaYearMonthEtrap',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Начисленный Год, Месяц и этрап для Доп. Услуги'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='internetNachisleniyaXlsxName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Добавленный xlsx файл имени интернет начисления в нашу БД'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='internetNachisleniyaYearMonthEtrapONOFF',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Начисленный Год, Месяц, Этрап  и ON/OFF Интернет начисления'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='internetPlatejiXlsxName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Добавленный xlsx файл имени внешние интернет платежи в нашу БД'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='kodNachisleniyaYearMonth',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Начисленный Год и Месяц для КОД'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='platejiNachisleniyaYearMonthEtrapONOFF',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Начисленный Год, Месяц, Этрап  и ON/OFF Внешние платежи'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='platejiSkassyKassirami',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='гггг-мм-дд  Платежи с файла биллинга в нашу кассу кассирами'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='slrNachisleniyaYearMonth',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Начисленный Год и Месяц для СЛР'),
        ),
        migrations.AlterField(
            model_name='dontrepeatyourself',
            name='zakazNachisleniaYearMonthEtrap',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Начисленный Год, Месяц и этрап для Заказных звонков'),
        ),
        migrations.AlterField(
            model_name='examgroup',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название Группы'),
        ),
        migrations.AlterField(
            model_name='examhistory',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='examhistory',
            name='surname',
            field=models.CharField(blank=True, max_length=500, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='importalemnachisleniyaoff',
            name='FAO',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='importalemnachisleniyaoff',
            name='dogowor',
            field=models.CharField(blank=True, max_length=100, verbose_name='№ Договора'),
        ),
        migrations.AlterField(
            model_name='importalemnachisleniyaoff',
            name='login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='importalemnachisleniyaon',
            name='FAO',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='importalemnachisleniyaon',
            name='dogowor',
            field=models.CharField(blank=True, max_length=100, verbose_name='№ Договора'),
        ),
        migrations.AlterField(
            model_name='importalemnachisleniyaon',
            name='login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='importinternetnachisleniyaoff',
            name='FAO',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='importinternetnachisleniyaoff',
            name='dogowor',
            field=models.CharField(blank=True, max_length=100, verbose_name='№ Договора'),
        ),
        migrations.AlterField(
            model_name='importinternetnachisleniyaoff',
            name='login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='importinternetnachisleniyaon',
            name='FAO',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='importinternetnachisleniyaon',
            name='dogowor',
            field=models.CharField(blank=True, max_length=100, verbose_name='№ Договора'),
        ),
        migrations.AlterField(
            model_name='importinternetnachisleniyaon',
            name='login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='importinternetplateji',
            name='FAO',
            field=models.CharField(max_length=1000, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='importinternetplateji',
            name='dogowor',
            field=models.CharField(max_length=100, verbose_name='№ Договора'),
        ),
        migrations.AlterField(
            model_name='importinternetplatejioff',
            name='FAO',
            field=models.CharField(max_length=1000, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='importinternetplatejioff',
            name='dogowor',
            field=models.CharField(max_length=100, verbose_name='№ Договора'),
        ),
        migrations.AlterField(
            model_name='internettarif',
            name='tarif',
            field=models.CharField(max_length=500, verbose_name='Скорость тарифа mb/s'),
        ),
        migrations.AlterField(
            model_name='interpayperekidkabilling',
            name='mtbUsername',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='MTB соотрудик'),
        ),
        migrations.AlterField(
            model_name='interpayperekidkabilling',
            name='name1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя 1'),
        ),
        migrations.AlterField(
            model_name='interpayperekidkabilling',
            name='name2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя 2'),
        ),
        migrations.AlterField(
            model_name='interpayperekidkabilling',
            name='operator',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Оператор который перекинул в billing'),
        ),
        migrations.AlterField(
            model_name='interpayperekidkabilling',
            name='surname1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Фамилия 1'),
        ),
        migrations.AlterField(
            model_name='interpayperekidkabilling',
            name='surname2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Фамилия 2'),
        ),
        migrations.AlterField(
            model_name='kabelcomment',
            name='action',
            field=models.CharField(choices=[('Изменения данных', 'Изменения данных'), ('Добавление абонента', 'Добавление абонента'), ('Удаление абонента', 'Удаление абонента')], max_length=500, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='kabelcomment',
            name='worker',
            field=models.CharField(max_length=500, verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='kabeltvnew',
            name='flat',
            field=models.CharField(blank=True, max_length=500, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='kabeltvnew',
            name='home',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='kabeltvnew',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='kabeltvnew',
            name='sotowyy',
            field=models.CharField(blank=True, max_length=500, verbose_name='Сотовый номер'),
        ),
        migrations.AlterField(
            model_name='kabeltvnew',
            name='street',
            field=models.CharField(blank=True, max_length=500, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='kabeltvnew',
            name='surname',
            field=models.CharField(blank=True, max_length=500, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='localcall',
            name='DUR',
            field=models.CharField(max_length=100, verbose_name='Длительность звонка'),
        ),
        migrations.AlterField(
            model_name='localcall',
            name='FIN',
            field=models.CharField(max_length=100, verbose_name='Конец звонка'),
        ),
        migrations.AlterField(
            model_name='localcall',
            name='MT',
            field=models.CharField(max_length=100, verbose_name='Общее минут разговора'),
        ),
        migrations.AlterField(
            model_name='localcall',
            name='START',
            field=models.CharField(max_length=100, verbose_name='Начало звонка'),
        ),
        migrations.AlterField(
            model_name='localcall',
            name='SUB_A',
            field=models.CharField(max_length=100, verbose_name='SUB_A номер'),
        ),
        migrations.AlterField(
            model_name='localcall',
            name='SUB_B',
            field=models.CharField(max_length=100, verbose_name='SUB_B номер'),
        ),
        migrations.AlterField(
            model_name='localcall',
            name='etrap',
            field=models.CharField(max_length=100, verbose_name='Этрап'),
        ),
        migrations.AlterField(
            model_name='managernames',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='managernames',
            name='name2',
            field=models.CharField(blank=True, max_length=500, verbose_name='Логин Менеджера'),
        ),
        migrations.AlterField(
            model_name='monthplatejifrombilling',
            name='FAO',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='monthplatejifrombilling',
            name='YurOrFiz',
            field=models.CharField(blank=True, max_length=500, verbose_name='Юридическое или Физическое лицо'),
        ),
        migrations.AlterField(
            model_name='monthplatejifrombilling',
            name='date_price',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дата вместо цены'),
        ),
        migrations.AlterField(
            model_name='monthplatejifrombilling',
            name='dogowor',
            field=models.CharField(max_length=500, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='monthplatejifrombilling',
            name='kod_oplaty',
            field=models.CharField(blank=True, max_length=500, verbose_name='Код оплаты'),
        ),
        migrations.AlterField(
            model_name='monthplatejifrombilling',
            name='manager',
            field=models.CharField(max_length=500, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='monthplatejifrombilling',
            name='platejiType',
            field=models.CharField(blank=True, max_length=500, verbose_name='Внешние платежи, default или Оплачено по карте'),
        ),
        migrations.AlterField(
            model_name='monthplatejiofffrombilling',
            name='FAO',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='monthplatejiofffrombilling',
            name='YurOrFiz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Юридическое или Физическое лицо'),
        ),
        migrations.AlterField(
            model_name='monthplatejiofffrombilling',
            name='date_price',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дата вместо цены'),
        ),
        migrations.AlterField(
            model_name='monthplatejiofffrombilling',
            name='dogowor',
            field=models.CharField(max_length=100, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='monthplatejiofffrombilling',
            name='kod_oplaty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код оплаты'),
        ),
        migrations.AlterField(
            model_name='monthplatejiofffrombilling',
            name='manager',
            field=models.CharField(max_length=500, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='monthplatejiofffrombilling',
            name='platejiType',
            field=models.CharField(blank=True, max_length=100, verbose_name='Внешние платежи, default или Оплачено по карте'),
        ),
        migrations.AlterField(
            model_name='nachislitwruchnuyuhistory',
            name='column',
            field=models.CharField(max_length=500, verbose_name='Начислил на'),
        ),
        migrations.AlterField(
            model_name='nachislitwruchnuyuhistory',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='nachislitwruchnuyuhistory',
            name='user',
            field=models.CharField(max_length=500, verbose_name='Работник который начислил'),
        ),
        migrations.AlterField(
            model_name='nachminus',
            name='dop_usligi_added_Pk',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='nachperekidkahistory',
            name='operator',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кто делал перекидку'),
        ),
        migrations.AlterField(
            model_name='nonlocalcall',
            name='DUR',
            field=models.CharField(max_length=500, verbose_name='Длительность звонка'),
        ),
        migrations.AlterField(
            model_name='nonlocalcall',
            name='FIN',
            field=models.CharField(max_length=500, verbose_name='Конец звонка'),
        ),
        migrations.AlterField(
            model_name='nonlocalcall',
            name='MT',
            field=models.CharField(max_length=500, verbose_name='Общее минут разговора'),
        ),
        migrations.AlterField(
            model_name='nonlocalcall',
            name='START',
            field=models.CharField(max_length=500, verbose_name='Начало звонка'),
        ),
        migrations.AlterField(
            model_name='nonlocalcall',
            name='SUB_A',
            field=models.CharField(max_length=500, verbose_name='SUB_A номер'),
        ),
        migrations.AlterField(
            model_name='nonlocalcall',
            name='SUB_A_etrap',
            field=models.CharField(max_length=500, verbose_name='SUB_A этрап'),
        ),
        migrations.AlterField(
            model_name='nonlocalcall',
            name='SUB_B',
            field=models.CharField(max_length=500, verbose_name='SUB_B номер'),
        ),
        migrations.AlterField(
            model_name='nonlocalcall',
            name='SUB_B_locations',
            field=models.CharField(max_length=500, verbose_name='SUB_B Город/Страна'),
        ),
        migrations.AlterField(
            model_name='nonlocalcall',
            name='edara',
            field=models.CharField(blank=True, max_length=500, verbose_name='H, B, или I'),
        ),
        migrations.AlterField(
            model_name='nonlocalcall',
            name='file_name',
            field=models.CharField(max_length=500, verbose_name='Названия файла'),
        ),
        migrations.AlterField(
            model_name='oldlogindogowor',
            name='dogowor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='oldlogindogowor',
            name='hb',
            field=models.CharField(blank=True, max_length=20, verbose_name='H или B'),
        ),
        migrations.AlterField(
            model_name='oldlogindogowor',
            name='login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='oldlogindogowor',
            name='operator',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кто сохранял в old'),
        ),
        migrations.AlterField(
            model_name='oldlogindogowor',
            name='saved_in_action',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Сохранено при действии'),
        ),
        migrations.AlterField(
            model_name='payandpaytypefordebitkredit',
            name='pay_type',
            field=models.CharField(max_length=500, verbose_name='Тип платежа (с кассы, TOLEG APP TMCELL, e-gov, и.т.п)'),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='kassa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Касса №'),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='kassir',
            field=models.CharField(max_length=500, verbose_name='Кассир'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user1KabelNameSurname',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Фамилия и имя во время перекидки kabel абонента 1'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user1Kflat',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Кабель1) Квартира'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user1Khome',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Кабель1) Дом'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user1Kname',
            field=models.CharField(blank=True, max_length=500, verbose_name='(Кабель1) Имя'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user1Kstreet',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Кабель1) Улица'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user1Ksurname',
            field=models.CharField(blank=True, max_length=500, verbose_name='(Кабель1) Фамилия'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user1NameSurname',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Фамилия и имя во время перекидки абонента 1'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user2Kflat',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Кабель2) Квартира'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user2Khome',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Кабель2) Дом'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user2Kname',
            field=models.CharField(blank=True, max_length=500, verbose_name='(Кабель2) Имя'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user2Kstreet',
            field=models.CharField(blank=True, max_length=100, verbose_name='(Кабель2) Улица'),
        ),
        migrations.AlterField(
            model_name='perekidkainfonew',
            name='user2Ksurname',
            field=models.CharField(blank=True, max_length=500, verbose_name='(Кабель2) Фамилия'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='dogowor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dogowor'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='file_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='kodOplaty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код оплаты'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='manager',
            field=models.CharField(blank=True, max_length=500, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='type_pay',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип платежа (абонплата, итернет, ...)'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='who_add_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кто добавил файл'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='abonplata',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Абонплата'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='flat',
            field=models.CharField(blank=True, max_length=500, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='flat_k',
            field=models.CharField(blank=True, max_length=500, verbose_name='Квартира Кабельное'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='home',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='home_k',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дом Кабельное'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Имя/Отдел'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='name_k',
            field=models.CharField(blank=True, max_length=500, verbose_name='Имя/Отдел Кабельное'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='street',
            field=models.CharField(blank=True, max_length=500, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='street_k',
            field=models.CharField(blank=True, max_length=500, verbose_name='Улица Кабельное'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='surname',
            field=models.CharField(blank=True, max_length=500, verbose_name='Фамилия/организация'),
        ),
        migrations.AlterField(
            model_name='saldobalancepogodam',
            name='surname_k',
            field=models.CharField(blank=True, max_length=500, verbose_name='Фамилия/организация Кабельное'),
        ),
        migrations.AlterField(
            model_name='saveinfoaboutwhoaddandnachpaysfrombilling',
            name='date_delete',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дата платежей для удаления'),
        ),
        migrations.AlterField(
            model_name='saveinfoaboutwhoaddandnachpaysfrombilling',
            name='who_add',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кто добавил'),
        ),
        migrations.AlterField(
            model_name='saveinfoaboutwhoaddandnachpaysfrombilling',
            name='who_nach',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кто начислил'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='q_lang',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Туркменский', 'Туркменский'), ('Русский', 'Русский')], max_length=500, verbose_name='Язык вопросов'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='surname',
            field=models.CharField(blank=True, max_length=500, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='snyatieinfo',
            name='namesurname1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Абонент при галочки'),
        ),
        migrations.AlterField(
            model_name='snyatieinfo',
            name='namesurname2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Абонент при снятии'),
        ),
        migrations.AlterField(
            model_name='snyatieinfo',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='snyatieinfo',
            name='operator_galochka',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кто ставил галочку'),
        ),
        migrations.AlterField(
            model_name='snyatieinfo',
            name='operator_snyal',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кто снял абонента'),
        ),
        migrations.AlterField(
            model_name='staffaction',
            name='action',
            field=models.CharField(choices=[('Delete', 'Delete'), ('Update', 'Update'), ('Recover', 'Recover'), ('Снятие Номера', 'Снятие Номера'), ('Безвозвратное удаление номера', 'Безвозвратное удаление номера'), ('Востановление номера', 'Востановление номера'), ('Начисления СЛР', 'Начисления СЛР'), ('Начисления КОД', 'Начисления КОД'), ('Начисления КОД+СЛР', 'Начисления КОД+СЛР'), ('Начисления Интернет Платежей', 'Начисления Интернет Платежей'), ('Импорт с xlsx внешние платежи в БД', 'Импорт с xlsx внешние платежи в БД'), ('Импорт с xlsx Интернет Начисления в БД', 'Импорт с xlsx Интернет Начисления в БД'), ('Импорт с xlsx Alem Начисления в БД', 'Импорт с xlsx Alem Начисления в БД'), ('Another', 'Another'), ('Начисления Интернет', 'Начисления Интернет'), ('Начисления абонплата', 'Начисления абонплата'), ('Начисления метры', 'Начисления метры'), ('Начисления заказ', 'Начисления заказ'), ('Начисления Доп Услуг', 'Начисления Доп Услуг'), ('Изменение Услуг', 'Изменение Услуг'), ('Подключения/смена интернет тарифа', 'Подключения/смена интернет тарифа'), ('Подключения/смена метров', 'Подключения/смена метров'), ('Кабель TV действия', 'Кабель TV действия'), ('Alem TV действия', 'Alem TV действия'), ('Изменение данных абонента в MATB в базе данных', 'Изменение данных абонента в MATB в базе данных'), ('Добавление абонента в MATB в базе данных', 'Добавление абонента в MATB в базе данных'), ('Перекидка', 'Перекидка'), ('Old Login Dogowor Save', 'Old Login Dogowor Save'), ('Old Login Dogowor Delete', 'Old Login Dogowor Delete'), ('Old Login Dogowor Update', 'Old Login Dogowor Update'), ('Добавления платежей в базу', 'Добавления платежей в базу'), ('Пробитие платежей с базы данных', 'Пробитие платежей с базы данных'), ('Ручное начисление', 'Ручное начисление')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='staffaction',
            name='akt_raport',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Акт, рапорт'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='abonplata',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Абонплата'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='accountAdress',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Адрес Счет номера (edara adress)'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='accountName',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Имя Счет номера (edara name)'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='dogowor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=500),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='flat',
            field=models.CharField(blank=True, max_length=500, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='home',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='ids',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кабель ID'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Имя/Отдел'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='number',
            field=models.CharField(max_length=500, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='sotowyy',
            field=models.CharField(blank=True, max_length=500, verbose_name='Сотовый номер'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='street',
            field=models.CharField(blank=True, max_length=500, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='surname',
            field=models.CharField(blank=True, max_length=500, verbose_name='Фамилия/организация'),
        ),
        migrations.AlterField(
            model_name='usertablearhiw',
            name='accountAdress',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Адрес Счет номера (edara adress)'),
        ),
        migrations.AlterField(
            model_name='usertablearhiw',
            name='accountName',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Имя Счет номера (edara name)'),
        ),
        migrations.AlterField(
            model_name='usertablearhiw',
            name='dogowor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='usertablearhiw',
            name='flat',
            field=models.CharField(blank=True, max_length=500, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='usertablearhiw',
            name='home',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='usertablearhiw',
            name='login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='usertablearhiw',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Имя/Отдел'),
        ),
        migrations.AlterField(
            model_name='usertablearhiw',
            name='street',
            field=models.CharField(blank=True, max_length=500, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='usertablearhiw',
            name='surname',
            field=models.CharField(blank=True, max_length=500, verbose_name='Фамилия/организация'),
        ),
        migrations.AlterField(
            model_name='ustanowkasnyatiedopuslughistory',
            name='user',
            field=models.CharField(max_length=500, verbose_name='Кто выполнил'),
        ),
        migrations.AlterField(
            model_name='ustanowkasnyatiedopuslughistory',
            name='which_action',
            field=models.CharField(max_length=1000, verbose_name='изменения при'),
        ),
        migrations.AlterField(
            model_name='ustanowkasnyatiedopuslughistory',
            name='which_type',
            field=models.CharField(max_length=1000, verbose_name='установлено/снято'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='CALL_TYPE',
            field=models.CharField(max_length=500, verbose_name='CALL_TYPE'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='DUR',
            field=models.CharField(max_length=500, verbose_name='DUR'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='NUMBER_A',
            field=models.CharField(max_length=500, verbose_name='NUMBER_A'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='NUMBER_B',
            field=models.CharField(max_length=500, verbose_name='NUMBER_B'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='NUMBER_LOCATIONS',
            field=models.CharField(max_length=500, verbose_name='Страна/Город соединяемой стороны'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='action',
            field=models.CharField(choices=[('', ''), ('бно', 'бно'), ('заказ подтвержден', 'заказ подтвержден')], max_length=500, verbose_name='бно/повторно/потдвержден'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=500, verbose_name='Этрап соединяющей стороны'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='price',
            field=models.CharField(max_length=500, verbose_name='цена за минуту без процента'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='total_price',
            field=models.CharField(max_length=500, verbose_name='Общая цена с процентом'),
        ),
    ]
