# Generated by Django 5.1.7 on 2025-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0076_alter_accountbalance_name_alter_accountname_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcall',
            name='edara',
            field=models.CharField(blank=True, max_length=500, verbose_name='H, B, или I'),
        ),
        migrations.AlterField(
            model_name='localcall',
            name='file_name',
            field=models.CharField(max_length=500, verbose_name='Названия файла'),
        ),
    ]
