# Generated by Django 5.1.7 on 2025-04-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0077_alter_localcall_edara_alter_localcall_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='kodOplaty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код оплаты'),
        ),
    ]
