# Generated by Django 5.1.7 on 2025-04-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0078_alter_platejiwhichaddkassirseveryday_kodoplaty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importinternetnachisleniyaon',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Год'),
        ),
    ]
