# Generated by Django 5.1.7 on 2025-04-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0079_alter_importinternetnachisleniyaon_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachminus',
            name='month',
            field=models.CharField(max_length=100, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='nachminus',
            name='year',
            field=models.CharField(max_length=100, verbose_name='Год'),
        ),
    ]
