# Generated by Django 5.1.7 on 2025-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0080_alter_nachminus_month_alter_nachminus_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaysWithComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер')),
                ('etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап')),
                ('operator', models.CharField(blank=True, max_length=256, verbose_name='Кто совершил платеж')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('internet', models.FloatField(default=0, verbose_name='Платеж на Интернет')),
                ('kabel', models.FloatField(default=0, verbose_name=' Платеж на Кабель')),
                ('alem', models.FloatField(default=0, verbose_name=' Платеж на Alem TV')),
                ('prochee', models.FloatField(default=0, verbose_name='Платеж на Телефон')),
            ],
            options={
                'verbose_name': 'Информация о платежах с коментариями',
                'verbose_name_plural': 'Информация о платежах с коментариями',
            },
        ),
    ]
