# Generated by Django 5.1.7 on 2025-04-25 09:22

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0081_payswithcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payswithcomment',
            name='changed',
            field=models.BooleanField(default=False, verbose_name='Отменили?'),
        ),
        migrations.AddField(
            model_name='payswithcomment',
            name='changed_comment',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='payswithcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Когда сделали платеж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payswithcomment',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 9, 22, 10, 190785), verbose_name='на какую дату сделали платеж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payswithcomment',
            name='when_changed',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 9, 22, 14, 614722), verbose_name='когда отменили'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payswithcomment',
            name='who_changed',
            field=models.CharField(blank=True, max_length=256, verbose_name='Кто отменил'),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='type',
            field=models.CharField(blank=True, choices=[(None, 'Внешние платежи или default (кассир)'), ('Внешние платежи', 'Внешние платежи'), ('Default', 'Default'), ('MATB', 'MATB')], max_length=128, null=True, verbose_name='Внешние платежи или Default (кассир)'),
        ),
    ]
