# Generated by Django 5.1.7 on 2025-04-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0082_payswithcomment_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payswithcomment',
            name='when_changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='когда отменили'),
        ),
    ]
