# Generated by Django 5.1.7 on 2025-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0083_alter_payswithcomment_when_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payswithcomment',
            name='pays_pk',
            field=models.CharField(blank=True, max_length=256, verbose_name='pk платежа (для отмены)'),
        ),
    ]
