# Generated by Django 5.1.7 on 2025-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0084_payswithcomment_pays_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payswithcomment',
            options={'verbose_name': 'Платеж с комментарием', 'verbose_name_plural': 'Платежи с комментариями'},
        ),
        migrations.AlterField(
            model_name='payswithcomment',
            name='alem',
            field=models.FloatField(default=0, verbose_name='Платеж на Alem TV'),
        ),
        migrations.AlterField(
            model_name='payswithcomment',
            name='kabel',
            field=models.FloatField(default=0, verbose_name='Платеж на Кабель'),
        ),
    ]
