# Generated by Django 5.1.7 on 2025-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0085_alter_payswithcomment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NachWithComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер')),
                ('etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап')),
                ('operator', models.CharField(blank=True, max_length=256, verbose_name='Кто сделал начисление')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('internet', models.FloatField(default=0, verbose_name='Начислен на Интернет')),
                ('kabel', models.FloatField(default=0, verbose_name='Начислен на Кабель')),
                ('alem', models.FloatField(default=0, verbose_name='Начислен на Alem TV')),
                ('prochee', models.FloatField(default=0, verbose_name='Начислен на prochee')),
                ('telefon', models.FloatField(default=0, verbose_name='Начислен на telefon')),
                ('slr', models.FloatField(default=0, verbose_name='Начислен на slr')),
                ('kod', models.FloatField(default=0, verbose_name='Начислен на kod')),
                ('zakaz', models.FloatField(default=0, verbose_name='Начислен на zakaz')),
                ('dop_uslugi', models.FloatField(default=0, verbose_name='Начислен на dop_uslugi')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Когда сделали начисления')),
                ('year', models.CharField(max_length=100, verbose_name='Год')),
                ('month', models.CharField(max_length=100, verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Начисления с комментарием',
                'verbose_name_plural': 'Начисления с комментариями',
            },
        ),
    ]
