# Generated by Django 5.1.7 on 2025-08-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0086_nachwithcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlemNachData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер телефона')),
                ('etrap', models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=500, null=True)),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('month', models.CharField(max_length=2, verbose_name='Месяц')),
                ('name', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Пользователь')),
                ('dogowor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Договор')),
                ('account_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Учетное имя')),
                ('tariff', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Тариф')),
                ('service', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Услуга')),
                ('tariff_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Списание по тарифу')),
                ('service_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Списание за услугу')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Кол-во (шт.)')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Итого')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Валюта')),
                ('on_off', models.CharField(blank=True, max_length=10, null=True, verbose_name='on_off')),
                ('file_name', models.CharField(blank=True, max_length=500, verbose_name='Файл')),
                ('is_nach', models.BooleanField(default=False, verbose_name='Начислен')),
            ],
        ),
        migrations.CreateModel(
            name='AlemNachFileNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=500, verbose_name='Файл')),
                ('add_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления Alem TV')),
                ('nach_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начисления Alem TV')),
                ('who_add', models.CharField(blank=True, max_length=500, verbose_name='Кто добавил')),
                ('who_nach', models.CharField(blank=True, max_length=500, verbose_name='Кто начислил')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('month', models.CharField(max_length=2, verbose_name='Месяц')),
                ('on_off', models.CharField(blank=True, max_length=10, null=True, verbose_name='on_off')),
                ('etrap', models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench')], max_length=500, null=True)),
            ],
        ),
    ]
