# Generated by Django 5.1.7 on 2025-12-24 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0087_alemnachdata_alemnachfilenames'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alemnachdata',
            name='etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alemnachfilenames',
            name='etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='importalemnachisleniyaoff',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32),
        ),
        migrations.AlterField(
            model_name='importalemnachisleniyaon',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32),
        ),
        migrations.AlterField(
            model_name='importinternetnachisleniyaoff',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32),
        ),
        migrations.AlterField(
            model_name='importinternetnachisleniyaon',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32),
        ),
        migrations.AlterField(
            model_name='importinternetplateji',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32),
        ),
        migrations.AlterField(
            model_name='importinternetplatejioff',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32),
        ),
        migrations.AlterField(
            model_name='interpayperekidkabilling',
            name='etrap1',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32, null=True, verbose_name='Этрап 1'),
        ),
        migrations.AlterField(
            model_name='interpayperekidkabilling',
            name='etrap2',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32, null=True, verbose_name='Этрап 2'),
        ),
        migrations.AlterField(
            model_name='interpayperekidkabilling',
            name='mtbEtrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=64, null=True, verbose_name='MTB соотрудик этрап'),
        ),
        migrations.AlterField(
            model_name='managernames',
            name='etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag'), ('Внешние платежи', 'Внешние платежи')], max_length=32, verbose_name='Этрап'),
        ),
        migrations.AlterField(
            model_name='monthbalance',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32, verbose_name='Этрап'),
        ),
        migrations.AlterField(
            model_name='nachisleniyaotchet',
            name='etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='nachislitwruchnuyuhistory',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32, verbose_name='Этрап абонента'),
        ),
        migrations.AlterField(
            model_name='nachmonthdebetkredet',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32, verbose_name='Этрап'),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='kassir_etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32, null=True, verbose_name='etrap кассира'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='kassir_etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag'), ('Внешние платежи', 'Внешние платежи')], max_length=32, verbose_name='Этрап кассира'),
        ),
        migrations.AlterField(
            model_name='platejiwhichaddkassirseveryday',
            name='user_etrap',
            field=models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32, verbose_name='Этрап абонента'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=500),
        ),
        migrations.AlterField(
            model_name='usertablearhiw',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ustanowkasnyatiedopuslughistory',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32, verbose_name='Этрап абонента'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='etrap',
            field=models.CharField(choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=500, verbose_name='Этрап соединяющей стороны'),
        ),
        migrations.CreateModel(
            name='ChangeBalanceWithComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер')),
                ('etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап')),
                ('surname', models.CharField(blank=True, max_length=500, verbose_name='Фамилия/организация')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Имя/Отдел')),
                ('street', models.CharField(blank=True, max_length=500, verbose_name='Улица')),
                ('home', models.CharField(blank=True, max_length=500, verbose_name='Дом')),
                ('flat', models.CharField(blank=True, max_length=500, verbose_name='Квартира')),
                ('operator', models.CharField(blank=True, max_length=256, verbose_name='Кто изменил баланс')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('old_balance', models.FloatField(default=0, verbose_name='Старый баланс')),
                ('new_balance', models.FloatField(default=0, verbose_name='Новый баланс')),
                ('change_type', models.CharField(choices=[('telefoniya', 'telefoniya'), ('internet', 'internet'), ('alem', 'alem'), ('kabel', 'kabel')], default='telefoniya', max_length=20, verbose_name='Тип')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Когда изменили баланс')),
                ('operatorFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил баланс (FK)')),
            ],
            options={
                'verbose_name': 'Изменение баланса с комментарием',
                'verbose_name_plural': 'Изменение баланса с комментариями',
            },
        ),
    ]
