# Generated by Django 5.1.7 on 2026-07-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0089_usertable_dogowor_alem_usertable_dogowor_belet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldlogindogowor',
            name='dogowor_alem',
            field=models.CharField(blank=True, max_length=100, verbose_name='Договор Алем ТВ'),
        ),
        migrations.AddField(
            model_name='oldlogindogowor',
            name='dogowor_belet',
            field=models.CharField(blank=True, max_length=100, verbose_name='Договор Белет'),
        ),
        migrations.AddField(
            model_name='oldlogindogowor',
            name='dogowor_telefoniya',
            field=models.CharField(blank=True, max_length=100, verbose_name='Договор Телефония'),
        ),
    ]
