# Generated by Django 5.1.7 on 2026-07-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0091_usertablearhiw_dogowor_alem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabeltvnew',
            name='dogowor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Договор'),
        ),
    ]
