# Generated by Django 5.1.7 on 2026-08-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0092_kabeltvnew_dogowor'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachminus',
            name='belet',
            field=models.FloatField(default=0, verbose_name='Белет'),
        ),
    ]
