# Generated by Django 5.1.7 on 2026-08-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0093_nachminus_belet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilliBillingPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='Номер абонента')),
                ('user_etrap', models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag')], max_length=32, verbose_name='Этрап абонента')),
                ('kassir_etrap', models.CharField(blank=True, choices=[(None, 'Этрап'), ('Dashoguz', 'Dashoguz'), ('Akdepe', 'Akdepe'), ('Gorogly', 'Gorogly'), ('Ruhubelent', 'Ruhubelent'), ('S.A.Nyyazow', 'S.A.Nyyazow'), ('Turkmenbashy', 'Turkmenbashy'), ('Boldumsaz', 'Boldumsaz'), ('Koneurgench', 'Koneurgench'), ('Garashsyzlyk', 'Garashsyzlyk'), ('Gubadag', 'Gubadag'), ('Внешние платежи', 'Внешние платежи')], max_length=32, verbose_name='Этрап кассира')),
                ('type_pay', models.CharField(blank=True, max_length=50, verbose_name='Тип платежа (Internet, Telefon, Alem, Kabel)')),
                ('is_matched', models.BooleanField(default=False, verbose_name='Абонент найден в базе')),
                ('payment_number', models.CharField(blank=True, max_length=100, verbose_name='Номер платежа Milli Billing')),
                ('depository_name', models.CharField(blank=True, max_length=200, verbose_name='Касса/терминал')),
                ('contract_code', models.CharField(blank=True, max_length=100, verbose_name='Номер договора (contractCode)')),
                ('subscriber_full_name', models.CharField(blank=True, max_length=300, verbose_name='ФИО абонента (из файла)')),
                ('tariff_group_name', models.CharField(blank=True, max_length=100, verbose_name='Категория услуги (tariffGroupName)')),
                ('currency_name', models.CharField(blank=True, max_length=50, verbose_name='Валюта')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('manager', models.CharField(blank=True, max_length=500, verbose_name='Менеджер')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата платежа')),
                ('price', models.FloatField(default=0, verbose_name='Сумма платежа')),
                ('file_name', models.CharField(blank=True, max_length=500, verbose_name='Файл')),
                ('who_add_file', models.CharField(blank=True, max_length=500, verbose_name='Кто добавил файл')),
                ('when_added_file', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда файл добавлен в БД')),
            ],
            options={
                'verbose_name': 'Платежи Milli Billing',
                'verbose_name_plural': 'Платежи Milli Billing',
            },
        ),
    ]
