# Generated by Django 5.1.7 on 2026-08-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0094_millibillingpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='millibillingpay',
            name='is_nach',
            field=models.BooleanField(default=False, verbose_name='Начислено в UserTable'),
        ),
    ]
