# Generated by Django 5.1.7 on 2026-08-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0095_millibillingpay_is_nach'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabeltvpayhistory',
            name='milli_billing_file_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Файл Milli Billing'),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='milli_billing_file_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Файл Milli Billing'),
        ),
    ]
