# Generated by Django 5.1.7 on 2026-08-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0096_kabeltvpayhistory_milli_billing_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckMilliBillingPaysWithKassirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап')),
                ('checked_kassir', models.CharField(blank=True, max_length=500, verbose_name='Проверенный кассир')),
                ('checked_date', models.CharField(blank=True, max_length=16, verbose_name='Какой день сверил')),
                ('day_is_closed', models.BooleanField(default=False, verbose_name='День Закрыт')),
                ('who_close_the_day', models.CharField(blank=True, max_length=500, verbose_name='Кто закрыл день')),
                ('operator', models.CharField(blank=True, max_length=500, verbose_name='Кто Проверил')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Когда проверил')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('total_telefon', models.FloatField(default=0, verbose_name='сумма телефонии')),
                ('total_alem', models.FloatField(default=0, verbose_name='сумма Alem')),
                ('total_internet', models.FloatField(default=0, verbose_name='сумма интернет')),
                ('total_kabel', models.FloatField(default=0, verbose_name='сумма кабель')),
                ('itogo_kassir', models.FloatField(default=0, verbose_name='itogo для этого кассира')),
                ('total_telefon_when_closed_day', models.FloatField(default=0, verbose_name='сумма телефонии за весь день (при закрытии дня)')),
                ('total_alem_when_closed_day', models.FloatField(default=0, verbose_name='сумма Alem за весь день (при закрытии дня)')),
                ('total_internet_when_closed_day', models.FloatField(default=0, verbose_name='сумма интернет за весь день (при закрытии дня)')),
                ('total_kabel_when_closed_day', models.FloatField(default=0, verbose_name='сумма кабель за весь день (при закрытии дня)')),
                ('itogo_when_closed_day', models.FloatField(default=0, verbose_name='итого за весь день (при закрытии дня)')),
            ],
            options={
                'verbose_name': 'Информация о сверках платежей Milli Billing',
                'verbose_name_plural': 'Информация о сверках платежей Milli Billing',
            },
        ),
    ]
