# Generated by Django 5.1.7 on 2026-08-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0097_checkmillibillingpayswithkassirs'),
    ]

    operations = [
        migrations.CreateModel(
            name='YhlasIyul2026InternetNach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=500, verbose_name='Пользователь (ФИО)')),
                ('dogowor', models.CharField(blank=True, max_length=100, verbose_name='Договор')),
                ('login', models.CharField(blank=True, max_length=100, verbose_name='Учетное имя')),
                ('arenda', models.FloatField(default=0, verbose_name='Аренда')),
                ('etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='Номер абонента')),
                ('is_enterprises', models.CharField(blank=True, max_length=10, verbose_name='Предприятия')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда добавлено')),
                ('who_add', models.CharField(blank=True, max_length=500, verbose_name='Кто добавил')),
                ('file_name', models.CharField(blank=True, max_length=500, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Yhlas Iyul 2026 Интернет начисление',
                'verbose_name_plural': 'Yhlas Iyul 2026 Интернет начисление',
            },
        ),
    ]
