# Generated by Django 5.1.7 on 2026-08-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0098_yhlasiyul2026internetnach'),
    ]

    operations = [
        migrations.AddField(
            model_name='yhlasiyul2026internetnach',
            name='is_nach',
            field=models.BooleanField(default=False, verbose_name='Начислено в NachMinus'),
        ),
    ]
