# Generated by Django 5.1.7 on 2026-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0099_yhlasiyul2026internetnach_is_nach'),
    ]

    operations = [
        migrations.AddField(
            model_name='yhlasiyul2026internetnach',
            name='nach_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда начислено'),
        ),
        migrations.AddField(
            model_name='yhlasiyul2026internetnach',
            name='who_nach',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кто начислил'),
        ),
    ]
