# Generated by Django 5.1.7 on 2026-08-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0100_yhlasiyul2026internetnach_nach_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Показывать на всех страницах')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда изменено')),
                ('updated_by', models.CharField(blank=True, max_length=500, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Сообщение админа (баннер на всех страницах)',
                'verbose_name_plural': 'Сообщение админа (баннер на всех страницах)',
            },
        ),
    ]
