# Generated by Django 5.1.7 on 2026-08-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0101_adminbroadcastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='yhlasiyul2026internetnach',
            name='service_type',
            field=models.CharField(choices=[('internet', 'Internet'), ('alem', 'Alem'), ('belet', 'Belet')], default='internet', max_length=20, verbose_name='Услуга'),
        ),
    ]
