# Generated by Django 5.1.7 on 2026-08-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0102_yhlasiyul2026internetnach_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='pays_from_billing_file_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Файл Pays From Billing'),
        ),
    ]
