# Generated by Django 5.1.7 on 2026-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0103_payhistory_pays_from_billing_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachwithcomment',
            name='belet',
            field=models.FloatField(default=0, verbose_name='Начислен на Belet'),
        ),
    ]
