# Generated by Django 5.1.7 on 2026-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telekom', '0105_yhlasiyul2026internetnach_year_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnceDogoworAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('belet', 'Belet')], default='belet', max_length=20, verbose_name='Услуга')),
                ('etrap', models.CharField(blank=True, max_length=64, verbose_name='Этрап')),
                ('fio', models.CharField(blank=True, max_length=500, verbose_name='Пользователь (ФИО)')),
                ('new_dogowor', models.CharField(blank=True, max_length=100, verbose_name='Новый договор (напр. Belet)')),
                ('search_dogowor', models.CharField(blank=True, max_length=100, verbose_name='Договор для поиска (напр. Internet)')),
                ('login', models.CharField(blank=True, max_length=100, verbose_name='Учетное имя')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='Номер абонента')),
                ('found_in', models.CharField(blank=True, choices=[('usertable', 'UserTable'), ('old', 'OldLoginDogowor')], max_length=16, verbose_name='Найден в')),
                ('previous_value', models.CharField(blank=True, max_length=100, verbose_name='Предыдущее значение поля (для отката)')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Применено в UserTable/Old?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда добавлено')),
                ('who_add', models.CharField(blank=True, max_length=500, verbose_name='Кто добавил')),
                ('file_name', models.CharField(blank=True, max_length=500, verbose_name='Файл')),
                ('who_apply', models.CharField(blank=True, max_length=500, verbose_name='Кто применил')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда применено')),
            ],
            options={
                'verbose_name': 'Once Dogowor Add',
                'verbose_name_plural': 'Once Dogowor Add',
            },
        ),
    ]
